name: comments

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  comments:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
